name: izowork
description: A new Flutter project.

publish_to: 'none'

version: 1.0.15+17

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  flutter_automation: ^2.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  intl: ^0.19.0
  hexcolor: ^3.0.1
  flutter_svg: any
  provider: ^6.1.2
  dio: ^5.7.0
  get_it: ^8.0.0
  badges: ^3.1.2
  modal_bottom_sheet: ^3.0.0
  scrollable_clean_calendar: ^1.5.0
  wheel_chooser: ^1.1.2
  blur: ^4.0.0
  oktoast: ^3.4.0
  cached_network_image: any
  image_picker: ^1.1.2
  adaptive_dialog: any
  chips_choice: ^3.0.1
  url_launcher: ^6.3.1
  fl_chart: ^0.69.0
  open_filex: ^4.5.0
  file_picker: ^8.1.2
  spreadsheet_table: ^1.0.0
  android_intent_plus: ^5.1.0
  flutter_image_slideshow: ^0.1.6
  socket_io_client: ^1.0.1
  record: ^5.1.2
  audioplayers: ^6.1.0
  # audiofileplayer: ^2.1.1
  audiofilereader: ^2.1.3
  simple_progress_indicators: ^0.2.0
  liquid_pull_to_refresh: ^3.0.1
  talker_flutter: ^4.4.1
  talker_dio_logger: ^4.4.1
  tab_container: ^3.5.3
  easy_debounce: ^2.0.3
  # flutter_phone_direct_caller: ^2.1.1
  insta_image_viewer: ^1.0.4

  geolocator: ^10.1.1
  google_maps_flutter: ^2.9.0
  google_place: ^0.4.7
  google_geocoding_api: ^1.5.2
  google_maps_cluster_manager_2: ^3.2.0

  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  flutter_local_notifications: ^17.2.3
  flutter_app_badge: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter_icons:
   android: 'launcher_icon'
   ios: true
   remove_alpha_ios: true
   image_path: 'assets/app_icon.png'

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/sounds/

  fonts:
    - family: PT Root UI
      fonts:
        - asset: fonts/PT_Root_UI_Bold.otf
          weight: 700
        - asset: fonts/PT_Root_UI_Medium.otf
          weight: 500
        - asset: fonts/PT_Root_UI_Regular.otf
          weight: 400
        - asset: fonts/PT_Root_UI_Light.otf
          weight: 300