const baseUrl = 'http://185.116.194.234/api/';
const socketUrl = '';
const productMedialUrl = baseUrl + 'resourses/product-image/';
const companyMedialUrl = baseUrl + 'resourses/company-image/';
const taskMediaUrl = baseUrl + 'resourses/task-file/';
const avatarUrl = baseUrl + 'resourses/avatar/';
const uploadAvatarUrl = baseUrl + 'user/avatar';
const loginUrl = baseUrl + 'auth/login';
const profileUrl = baseUrl + 'user/me';
const usersUrl = baseUrl + 'user/all';
const userUrl = baseUrl + 'user/one';
const userUpdateUrl = baseUrl + 'user/profile';
const productUrl = baseUrl + 'product/one?id=';
const productsUrl = baseUrl + 'product/all';
const productTypesUrl = baseUrl + 'product-type/all';
const companyUrl = baseUrl + 'company/one?id=';
const companiesUrl = baseUrl + 'company/all';
const companyTypesUrl = baseUrl + 'company/types';
const companyCreateUrl = baseUrl + 'company/create';
const uploadCompanyUrl = baseUrl + 'company/image';
const taskUrl = baseUrl + 'task/one?id=';
const tasksUrl = baseUrl + 'task/all';
const taskCreateUrl = baseUrl + 'task/create';
const taskUpdateUrl = baseUrl + 'task/update';
const taskFileUrl = baseUrl + 'task/file';
const taskStatesUrl = baseUrl + 'task/states';
const dealUrl = baseUrl + 'deal/one?id=';
const dealsUrl = baseUrl + 'deal/all';
const objectUrl = baseUrl + 'object/one?id=';
const objectsUrl = baseUrl + 'object/all';
const objectCreateUrl = baseUrl + 'object/create';
const objectUpdateUrl = baseUrl + 'object/update';
const objectTypesUrl = baseUrl + 'object-type/all';
const objectStatesUrl = baseUrl + 'object-stage/all';
const objectMediaUrl = baseUrl + 'resourses/object-file/';
const phaseUrl = baseUrl + 'phase/all';
const phaseProductsUrl = baseUrl + 'phase/product/all';
const phaseContractorsUrl = baseUrl + 'phase/contractor/all';
const phaseChecklistUrl = baseUrl + 'phase/checklist/all';
const phaseChecklistInformationUrl =
    baseUrl + 'phase/checklist/information/all';
const phaseChecklistInformationCreateUrl =
    baseUrl + 'phase/checklist/information/create';
const phaseChecklistInformationFileUrl =
    baseUrl + 'phase/checklist/information/file';
const phaseChecklistInformationMediaUrl =
    baseUrl + 'resourses/checklist-information-file/';
const phaseContractorCreateUrl = baseUrl + 'phase/contractor/create';
const phaseChecklistStateUpdateUrl = baseUrl + 'phase/checklist/update';
const phaseContractorUpdateUrl = baseUrl + 'phase/contractor/update';
const phaseContractorDeleteUrl = baseUrl + 'phase/contractor/delete';
const phaseProductCreateUrl = baseUrl + 'phase/product/create';
const phaseProductUpdateUrl = baseUrl + 'phase/product/update';
const phaseProductDeleteUrl = baseUrl + 'phase/product/delete';
